// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoL2n3t7Wlxq_a4cDU9W0_aYuaLLIdME',
    appId: '1:982977699496:web:30d6f3474b299571bfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    authDomain: 'donnavita-cc447.firebaseapp.com',
    storageBucket: 'donnavita-cc447.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmkqQnoRMFJDCyNf1zvoBRLCEWPc9pa4',
    appId: '1:982977699496:android:e86527587689320dbfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    storageBucket: 'donnavita-cc447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkNjejqBEjMBPk0SvXliDHyEf48AjPBI0',
    appId: '1:982977699496:ios:fde26dff83f02a2dbfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    storageBucket: 'donnavita-cc447.appspot.com',
    iosBundleId: 'com.example.projectfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkNjejqBEjMBPk0SvXliDHyEf48AjPBI0',
    appId: '1:982977699496:ios:99608a6d02f8a3c9bfec9d',
    messagingSenderId: '982977699496',
    projectId: 'donnavita-cc447',
    storageBucket: 'donnavita-cc447.appspot.com',
    iosBundleId: 'com.example.projectfinal.RunnerTests',
  );
}
